### ISSUE TITLE
Website, forum?

### ISSUE THREAD

**Issue by poetaster** [sebiik/axoloti#2]
It looks like we may have issues with the old forum. I could help with a forum for noloti. I have space and bandwidth. Otherwise, still haven't got to final assembly of the prototypes, but all the tests worked ;)

**Comment by sebiik** [comment]
I have since been backing up the Axoloti forum at [sebiik.github.io/community.axoloti.com.backup/ ](https://sebiik.github.io/community.axoloti.com.backup/)
It's not easy to catch all threads because the forum is dying tiny deaths all the time (apart from the 502-induced comas)  
Are you familiar with implementing a simple search function on the website? I tried.to paste a simple Google search thing following a tutorial but it does not show any results

**Comment by poetaster** [comment]
I think to get the google search widget to work you have to set it up to search the correct url:
```<script type="application/ld+json">{"@context":"http://schema.org","@type":"WebSite","url":"http://community.axoloti.com","potentialAction":{"@type":"SearchAction","target":"http://community.axoloti.com/search?q={search_term_string}","query-input":"required name=search_term_string"}}</script>```

Still points to the original so google won't show any results since that'd be a cross-site scripting hack :) I'll take a look a setting up discourse on one of my servers. I assume you scraped the html?

**Comment by UltraBlackLinux** [comment]
Another way to fix the google widget is to just supply google with `site:<the url> <query>`, that's how techpowerup does it anyway

**Comment by sebiik** [comment]
I am starting to suspect that the domain github.io is not indexed by google. Neither a regular search via google.com nor the search bar on the forum backup provide any results. I am trying a "google search console verification" thing, let's see if this will start indexing the content.

**Comment by UltraBlackLinux** [comment]
> Found that your website or web page isn’t indexed in Google? Try this:

 >   Go to Google Search Console
    Navigate to the URL inspection tool
    Paste the URL you’d like Google to index into the search bar.
    Wait for Google to check the URL
    Click the “Request indexing” button

https://search.google.com/search-console/about

Maybe try this

**Comment by sebiik** [comment]
Oh ya I did this weeks ago, wondering if the indexing gets reset everytime I update the repository?

**Comment by UltraBlackLinux** [comment]
it really shouldn't. Are you sure it was ever working?

**Comment by sebiik** [comment]
Nah, it was never working. Not even via google.com search

**Comment by rekado** [comment]
You could use https://github.com/olivernn/lunr.js to index all pages and provide a search for the archive.  Is the repository backing https://sebiik.github.io/community.axoloti.com.backup/ available here?

**Comment by sebiik** [comment]
> https://sebiik.github.io/community.axoloti.com.backup/ available here?

Yes, it's over at 
https://github.com/sebiik/community.axoloti.com.backup
It's a few GB in size, as a heads up

If you come up with a way to check and fix up missing files, that would be most welcome. Especially some of the patch files are missing, would be great to have those back.

By the way, c.f. this post
https://llllllll.co/t/axoloti-core-derivatives/3591/357?u=sebiik
The goodies are still there, only the front door is locked!

**Comment by ksoloti** [comment]
New Ksoloti forum has been created at https://ksoloti.discourse.group
